### ISSUE TITLE
The outline is not populated

### ISSUE THREAD

**Issue by ylussaud** [eclipse-acceleo/acceleo#167]
This is a regression. Maybe related to the LSP4E version update.

**Comment by ylussaud** [comment]
The outline is populated in my development environment... it's probably a packaging issue.

**Comment by ylussaud** [comment]
LSP4E 0.18.12 use the class `org.eclipse.ui.views.WorkbenchViewerSetup` from the plugin `org.eclipse.ui.workbench`. This class was introduced in version 3.130 of the plugin. The outline can't word with older versions.

```
java.lang.NoClassDefFoundError: org/eclipse/ui/views/WorkbenchViewerSetup
	at org.eclipse.lsp4e.outline.LSSymbolsContentProvider.inputChanged(LSSymbolsContentProvider.java:293)
	at org.eclipse.ui.internal.navigator.extensions.SafeDelegateTreeContentProvider$2.run(SafeDelegateTreeContentProvider.java:128)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
	at org.eclipse.ui.internal.navigator.extensions.SafeDelegateTreeContentProvider.inputChanged(SafeDelegateTreeContentProvider.java:125)
	at org.eclipse.ui.internal.navigator.extensions.StructuredViewerManager$1.run(StructuredViewerManager.java:193)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
	at org.eclipse.ui.internal.navigator.extensions.StructuredViewerManager.initialize(StructuredViewerManager.java:189)
	at org.eclipse.ui.internal.navigator.extensions.NavigatorContentExtension$1.run(NavigatorContentExtension.java:120)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
	at org.eclipse.ui.internal.navigator.extensions.NavigatorContentExtension.internalGetContentProvider(NavigatorContentExtension.java:109)
	at org.eclipse.ui.internal.navigator.NavigatorContentService.extractContentProviders(NavigatorContentService.java:1110)
	at org.eclipse.ui.internal.navigator.NavigatorContentService.updateService(NavigatorContentService.java:360)
	at org.eclipse.ui.internal.navigator.NavigatorContentServiceContentProvider.inputChanged(NavigatorContentServiceContentProvider.java:113)
	at org.eclipse.jface.viewers.ContentViewer.setInput(ContentViewer.java:278)
	at org.eclipse.jface.viewers.StructuredViewer.setInput(StructuredViewer.java:1632)
	at org.eclipse.lsp4e.outline.CNFOutlinePage.createControl(CNFOutlinePage.java:91)
	at org.eclipse.ui.views.contentoutline.ContentOutline.doCreatePage(ContentOutline.java:141)
	at org.eclipse.ui.part.PageBookView.createPage(PageBookView.java:369)
	at org.eclipse.ui.part.PageBookView.partActivated(PageBookView.java:696)
	...
Caused by: java.lang.ClassNotFoundException: org.eclipse.ui.views.WorkbenchViewerSetup cannot be found by org.eclipse.lsp4e_0.18.12.202408150719
	at org.eclipse.osgi.internal.loader.BundleLoader.generateException(BundleLoader.java:541)
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass0(BundleLoader.java:536)
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:416)
	at org.eclipse.osgi.internal.loader.ModuleClassLoader.loadClass(ModuleClassLoader.java:168)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:525)
	... 99 more

```

One workaround could be to downgrave the version of LSP4E we are using. But it doesn't sound like a good idea.
